# Generated by Django 4.0.4 on 2022-06-25 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerModel',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default=True, max_length=200)),
                ('mobile', models.BigIntegerField(default=True)),
                ('email', models.EmailField(default=True, max_length=254)),
                ('profile', models.ImageField(null=True, upload_to='owner/')),
                ('pwd', models.CharField(max_length=20, null=True)),
                ('cpwd', models.CharField(max_length=20, null=True)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('otp', models.TextField(null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('verification', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'db_table': 'owner_details',
            },
        ),
        migrations.CreateModel(
            name='UploadDocumentsModel',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.ImageField(null=True, upload_to='files/')),
                ('doc_type', models.TextField(null=True)),
                ('doc_size', models.BigIntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('doc_name', models.TextField(null=True)),
                ('enc_doc_name', models.TextField(null=True)),
                ('random_keys', models.TextField(null=True)),
                ('file_enc_key', models.TextField(null=True)),
                ('file_data', models.TextField(null=True)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('status', models.TextField(default='pending')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ownerapp.ownermodel')),
            ],
            options={
                'db_table': 'upload_documents',
            },
        ),
    ]
