# Generated by Django 4.0.4 on 2022-06-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddocumentsmodel',
            name='download_rank',
            field=models.IntegerField(null=True),
        ),
    ]
