# Generated by Django 4.0.4 on 2022-06-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRequestModel',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('doc_id', models.IntegerField(null=True)),
                ('document', models.FileField(upload_to='files/')),
                ('doc_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250, null=True)),
                ('doc_size', models.BigIntegerField(null=True)),
                ('doc_type', models.CharField(max_length=300)),
                ('file_enc_key', models.TextField(null=True)),
                ('secure_key', models.CharField(max_length=100, null=True)),
                ('request_status', models.CharField(default='pending', max_length=50, null='True')),
                ('download_status', models.CharField(default='pending', max_length=200, null=True)),
                ('requested_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user_download_requests',
            },
        ),
        migrations.CreateModel(
            name='DownloadsModel',
            fields=[
                ('download_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('doc_id', models.IntegerField(null=True)),
                ('status', models.CharField(default='pending', max_length=200, null=True)),
                ('download_rank', models.IntegerField(null=True)),
                ('downloaded_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'document_downloads',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default=True, max_length=200)),
                ('mobile', models.BigIntegerField(default=True)),
                ('email', models.EmailField(default=True, max_length=254)),
                ('profile', models.ImageField(null=True, upload_to='user/')),
                ('pwd', models.CharField(max_length=20, null=True)),
                ('cpwd', models.CharField(max_length=20, null=True)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('otp', models.TextField(null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
