# Generated by Django 4.0.4 on 2022-06-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadsmodel',
            name='req_id',
            field=models.IntegerField(null=True),
        ),
    ]
