# Generated by Django 4.0.4 on 2022-06-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_downloadsmodel_req_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadsmodel',
            name='download_rank',
        ),
    ]
